spring:
  profiles:
    active: nosecurity
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3  # ← RÉDUIRE À 3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # ← DÉSACTIVER

# RÉDUIRE AU MAXIMUM LES LOGS
logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    tunutech.api: WARN
    com.zaxxer.hikari: WARN