spring:
  main:
    allow-bean-definition-overriding: true  # ‚Üê AJOUTEZ CETTE LIGNE
  profiles:
    active: nosecurity
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuration DataSource pour Railway
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/localdb}
    driver-class-name: org.postgresql.Driver